# Autogenerated wrapper script for libserialport_jll for x86_64-w64-mingw32
export libserialport

JLLWrappers.@generate_wrapper_header("libserialport")
JLLWrappers.@declare_library_product(libserialport, "libserialport-0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libserialport,
        "bin\\libserialport-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
